version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - koopbis-net
    ports:
      - 5433:5432

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - cooperative-service
      - partner-service
    networks:
      - koopbis-net

  auth-service:
    build: ./services/auth-service
    ports:
      - "8081:8081"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: postgres
    depends_on:
      - postgres
    networks:
      - koopbis-net

  cooperative-service:
    build: ./services/cooperative-service
    ports:
      - "8082:8082"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: postgres
    depends_on:
      - postgres
    networks:
      - koopbis-net

  partner-service:
    build: ./services/partner-service
    ports:
      - "8083:8083"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: postgres
    depends_on:
      - postgres
    networks:
      - koopbis-net

  frontend:
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - api-gateway
    networks:
      - koopbis-net

volumes:
  db_data:

networks:
  koopbis-net:
    driver: bridge
